package com.github.SalindaGunarathna.tests;

import com.github.SalindaGunarathna.processor.DtoProcessor;
import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import com.google.testing.compile.JavaFileObjects;
import org.junit.jupiter.api.Test;

import javax.tools.JavaFileObject;
import java.io.IOException;

import static com.google.testing.compile.CompilationSubject.assertThat;

/**
 * Class-level generateToEntity configuration tests.
 * Verifies toEntity generation on/off, mixed DTO configs, and compile-time failures.
 */
public class DtoGenerateToEntityConfigTest {

    /**
     * Verifies toEntity is generated by default when generateToEntity is not set.
     */
    @Test
    void generateToEntity_defaultTrue_generatesToEntity() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        String mapper = getGeneratedSource(compilation, "com.example.model.mapper.user.UserDtoMapper");
        com.google.common.truth.Truth.assertThat(mapper)
                .contains("toEntity(");
    }

    /**
     * Verifies toEntity is not generated when generateToEntity is false.
     */
    @Test
    void generateToEntity_false_skipsToEntity() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\", generateToEntity = false)",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        String mapper = getGeneratedSource(compilation, "com.example.model.mapper.user.UserDtoMapper");
        com.google.common.truth.Truth.assertThat(mapper)
                .doesNotContain("toEntity(");
    }

    /**
     * Verifies per-DTO configuration: one mapper has toEntity while another does not.
     */
    @Test
    void generateToEntity_mixedPerDto_onlyGeneratesForEnabled() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserCreateDto\", generateToEntity = false)",
                "@Dto(name = \"UserResponseDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserCreateDto\", \"UserResponseDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        String createMapper = getGeneratedSource(compilation, "com.example.model.mapper.user.UserCreateDtoMapper");
        String responseMapper = getGeneratedSource(compilation, "com.example.model.mapper.user.UserResponseDtoMapper");
        com.google.common.truth.Truth.assertThat(createMapper)
                .doesNotContain("toEntity(");
        com.google.common.truth.Truth.assertThat(responseMapper)
                .contains("toEntity(");
    }

    /**
     * Verifies compilation fails when toEntity requires a missing entity setter.
     */
    @Test
    void generateToEntity_missingSetter_failsCompilation() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).failed();
        assertThat(compilation).hadErrorContaining("setEmail");
    }

    /**
     * Verifies compilation fails when toEntity uses a setter with mismatched types.
     */
    @Test
    void generateToEntity_setterTypeMismatch_failsCompilation() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(Integer email) { }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).failed();
        assertThat(compilation).hadErrorContaining("incompatible types");
    }

    private static String getGeneratedSource(Compilation compilation, String qualifiedName) {
        JavaFileObject file = compilation.generatedSourceFile(qualifiedName)
                .orElseThrow(() -> new AssertionError("Missing generated source: " + qualifiedName));
        try {
            return file.getCharContent(false).toString();
        } catch (IOException e) {
            throw new AssertionError("Failed to read generated source: " + qualifiedName, e);
        }
    }
}
