package com.github.SalindaGunarathna.tests;

import com.github.SalindaGunarathna.processor.DtoProcessor;
import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import com.google.testing.compile.JavaFileObjects;
import org.junit.jupiter.api.Test;

import javax.tools.JavaFileObject;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Class-level generateMapper configuration tests.
 * Verifies mapper generation on/off behavior and common error scenarios.
 */
public class DtoGenerateMapperConfigTest {

    /**
     * Verifies mappers are generated by default when generateMapper is not set.
     */
    @Test
    void generateMapper_defaultTrue_generatesMapper() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        assertTrue(hasGeneratedFile(compilation, "com/example/model/mapper/user/UserDtoMapper.java"));
    }

    /**
     * Verifies mappers are not generated when generateMapper is false.
     */
    @Test
    void generateMapper_false_skipsMapperGeneration() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\", generateMapper = false)",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        assertFalse(hasGeneratedFile(compilation, "com/example/model/mapper/user/UserDtoMapper.java"));
    }

    /**
     * Verifies per-DTO configuration: one mapper is generated while another is skipped.
     */
    @Test
    void generateMapper_mixedPerDto_onlyGeneratesForEnabled() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserCreateDto\", generateMapper = false)",
                "@Dto(name = \"UserResponseDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserCreateDto\", \"UserResponseDto\"})",
                "  private String email;",
                "  public String getEmail() { return email; }",
                "  public void setEmail(String email) { this.email = email; }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).succeeded();
        assertFalse(hasGeneratedFile(compilation, "com/example/model/mapper/user/UserCreateDtoMapper.java"));
        assertTrue(hasGeneratedFile(compilation, "com/example/model/mapper/user/UserResponseDtoMapper.java"));
    }

    /**
     * Verifies compilation fails when entity accessors required by the mapper are missing.
     */
    @Test
    void generateMapper_missingAccessors_failsCompilation() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).failed();
        assertThat(compilation).hadErrorContaining("getEmail");
    }

    /**
     * Verifies compilation fails when entity accessor types do not match the DTO field type.
     */
    @Test
    void generateMapper_mismatchedAccessorTypes_failsCompilation() {
        JavaFileObject source = JavaFileObjects.forSourceLines(
                "com.example.model.User",
                "package com.example.model;",
                "import com.github.SalindaGunarathna.annotations.Dto;",
                "import com.github.SalindaGunarathna.annotations.IncludeInDto;",
                "@Dto(name = \"UserDto\")",
                "public class User {",
                "  @IncludeInDto(dtos = {\"UserDto\"})",
                "  private String email;",
                "  public int getEmail() { return 0; }",
                "  public void setEmail(int email) { }",
                "}"
        );

        Compilation compilation = Compiler.javac()
                .withProcessors(new DtoProcessor())
                .compile(source);

        assertThat(compilation).failed();
        assertThat(compilation).hadErrorContaining("incompatible types");
    }

    private static boolean hasGeneratedFile(Compilation compilation, String suffix) {
        return compilation.generatedSourceFiles().stream()
                .map(file -> file.toUri().toString().replace("\\", "/"))
                .anyMatch(path -> path.endsWith(suffix));
    }
}
